---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(plotly)
library(hrbrthemes)
library(gcookbook)
library(paletteer)
library(pals)
library(showtext)
library(cowplot)
library(widgetframe)
library(trelliscopejs)

source("data_load.R")

font_add_google("Titillium Web","Titillium")
font_add("Arial Narrow","Arial Narrow")

showtext_auto()
```



```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
most_voted2017 <- resultados2017_analisis$Diputados$resultados %>% left_join(partidos %>% filter(eleccion==2017),by="Partido") %>%
                  mutate(Partido=Partido_Corrected) %>% select(-Partido_Corrected,-Nota,-eleccion) %>% group_by(Comuna) %>%
                  slice_max(Votos) %>% ungroup() %>%
                  select(Comuna,PartidoMasVotado=Partido,VotosMasVotado=Votos)

data1<- resultados2017_analisis$Diputados$resultados  %>% group_by(Comuna) %>%
                  summarise(Votos=sum(Votos)) %>% ungroup() %>% 
                  left_join(resultados2017_analisis$Diputados$electores,by="Comuna") %>%
                  mutate(Participacion_2107=Votos/Electores) %>% 
                  left_join(most_voted2017,by="Comuna") %>%
                  mutate(Comuna_Servel=Comuna,
                         MasVotado_Per=VotosMasVotado/Votos) %>% select(-Comuna,-Electores) %>%
                  left_join(plebiscito2020,by="Comuna_Servel")



p<-  data1 %>% 
            mutate(`Porcentaje Más Votado en 2017`=MasVotado_Per*100,
                   `Porcentaje Apruebo 2020`=Apruebo_per,
                   `Porcentaje Participaciòn 2020`=Participacion_per*100) %>% 
            ggplot(aes(`Porcentaje Más Votado en 2017`,`Porcentaje Apruebo 2020`,
                       colour=`Porcentaje Participaciòn 2020`,group=Comuna)) + geom_point() + 
#            geom_abline(slope=1, intercept=0,color="orange",type="dashed") +
             geom_hline(yintercept=50, intercept=0,color="orange",linetype="dotted") +
             geom_vline(xintercept=50, intercept=0,color="orange",linetype="dotted") +
  theme_minimal() +
  theme(legend.position="bottom",
        plot.title = element_text(size=16,face="bold",colour = "#272928",family="Titillium"),
        plot.subtitle =element_text(size=10,colour = "azure4",family="Titillium"),
        plot.caption =  element_text(size=10,colour = "azure4",family="Titillium"),
        legend.text = element_text(size=10,colour = "#272928",family="Titillium"),
        strip.text = element_text(face = "bold", color = "azure4",
                                  hjust = 0, size = 8,family="Titillium"),
        strip.background = element_rect(fill = "#fcf8f7",linetype = "blank")) +
  labs(title="Plebiscito 2020 - Comparación con elección Diputados 2017",
       subtitle="Comunas divididas por partido más votado en 2017",
       x="Porcentaje partido más votado 2017",
       y= "Porcentaje Apruebo en 2020",
       caption="Fuente: servel.cl | www.carlosyanez.cl",
       colour="Participación 2020 (votos/electores)") +
  scale_color_paletteer_c("pals::coolwarm") +
   facet_wrap(PartidoMasVotado ~. ,ncol=3) 



ggsave("plot.png",p)

htmlwidgets::saveWidget(frameableWidget(ggplotly(p)), "plebiscito_plot.html")
ggplotly(p)
```


```{r}

#data1<- resultados2017_analisis$Diputados$resultados  %>% group_by(Comuna) %>%
#                  summarise(Votos=sum(Votos)) %>% ungroup() %>% 
#                  left_join(resultados2017_analisis$Diputados$electores,by="Comuna") %>%
#                  mutate(Participacion_2107=Votos/Electores) %>% 
#                  left_join(most_voted2017,by="Comuna") %>%
#                  mutate(Comuna_Servel=Comuna,
#                         MasVotado_Per=VotosMasVotado/Votos) %>% select(-Comuna,-Electores) %>%
#                  left_join(plebiscito2020,by="Comuna_Servel")



p<-  data1 %>% 
            mutate(`Porcentaje Participacion 2017`=Participacion_2107*100,
                   `Porcentaje Apruebo 2020`=Apruebo_per,
                   `Porcentaje Participaciòn 2020`=Participacion_per*100) %>% 
            ggplot(aes(`Porcentaje Participacion 2017`,`Porcentaje Participaciòn 2020`,
                       colour=`Porcentaje Apruebo 2020`,group=Comuna,size=Electores)) + geom_point() + 
#            geom_abline(slope=1, intercept=0,color="orange",type="dashed") +
             geom_hline(yintercept=50, intercept=0,color="orange",linetype="dotted") +
             geom_vline(xintercept=50, intercept=0,color="orange",linetype="dotted") +
  theme_minimal() +
  theme(legend.position="bottom",
        plot.title = element_text(size=16,face="bold",colour = "#272928",family="Titillium"),
        plot.subtitle =element_text(size=10,colour = "azure4",family="Titillium"),
        plot.caption =  element_text(size=10,colour = "azure4",family="Titillium"),
        legend.text = element_text(size=10,colour = "#272928",family="Titillium"),
        strip.text = element_text(face = "bold", color = "azure4",
                                  hjust = 0, size = 8,family="Titillium"),
        strip.background = element_rect(fill = "#fcf8f7",linetype = "blank")) +
  labs(title="Plebiscito 2020 - Comparación con elección Diputados 2017",
       subtitle="Comunas divididas por partido más votado en 2017",
       x="Porcentaje partido más votado 2017",
       y= "Porcentaje Apruebo en 2020",
       caption="Fuente: servel.cl | www.carlosyanez.cl",
       colour="Participación 2020 (votos/electores)") +
  scale_color_paletteer_c("pals::coolwarm",direction=-1) +

   facet_trelliscope(Region ~. ,ncol=1) 



#ggsave("plot.png",p)

#htmlwidgets::saveWidget(frameableWidget(ggplotly(p)), "plebiscito_plot.html")
p
```

